---
name: Spotify Connect
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/techexplorers123/addon-spotify-connect
codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armv7
host-networking: true
audio: true
init: false
map:
  - addon_config:rw
options:
  name: Home Assistant
  bitrate: 160
  initial_volume: 50
  autoplay: true
  oauth: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  oauth: bool
  autoplay: bool
  initial_volume: match(^([0-9]|[1-9][0-9]|100)$)?
